### PR TITLE
fixed port is not detects without host.

### PR DESCRIPTION
**Pull request by xiaofan9**
_for example:_ 
old :
```
// my-server
let server  = net.createServer(function(){});
server.listen(3000);

portfinder.basePort = 3000;
portfinder.getPort(function(error, port) {
// port -> 3000
});
```

now :
```
// my-server
let server  = net.createServer(function(){});
server.listen(3000);

portfinder.basePort = 3000;
portfinder.getPort(function(error, port) {
// port -> 3001
});

```
**Has passed the test.**

### CODE REVIEW

**Comment by eriktrom** [comment]
i think this is going to fix windows 10 issues - on linux undefined is automatically passed, on windows I've heard (through other issues and the grapevine) that '*' is passed when no host is provided.

Is that the intent of this pr, or did u have issues in posix based shell that i should also know about?

**Comment by eriktrom** [comment]
going to merge, but let know what your env(shell) is before i publish so i know if this was for another bug that i was not aware of, thanks.

**Comment by xiaofan9** [comment]
@eriktrom PR Intention is going to  fix windows 10 issues

**Comment by eriktrom** [comment]
@xiaofan9 - awesome thank you - its been released with 1.0.17

**Pull request merged**
