### PR TITLE
Add appveyor

### PR DESCRIPTION
**Pull request by eriktrom**
Add appveyor.yml to test against windows in CI

### CODE REVIEW

**Comment by eriktrom** [comment]
@indexzero - do you want to add the appveyor integration on your side, no need for commit bit

once you do this will fail for the socket test but pass for the others (the socket support was not altered by #20) so could use your thoughts here

i'll push another commit that will show that it passes for non socket tests

fyi - @stefanpenner

**Comment by eriktrom** [comment]
to summarize there are 2 issues we need to address:

- how to make the socket tests pass with appvoyer (non regression, just life bug)
- whether our tests cover the use case in #21, and if not, what tests to add to get the reported there

**Comment by eriktrom** [comment]
@indexzero - this is closer - on appveyor we now only have one failing test, the same one as we have on travis above(im not done with the socket test, fyi, the cleanup using windows friendly node methods is WIP) and I believe #23 may have taken care #21 (although this is a hunch, but seems likely)

i'll be back at a later date :)

**Comment by indexzero** [comment]
@eriktrom glad to hear you're making progress. Happy to give you commit bit here if you'd like. Sounds like you've got this situation under control :smile: :+1:

**Comment by eriktrom** [comment]
@indexzero - I agree with a comment you made, we really need good tests. This is almost ready, but creating the servers within the socket tests throw - I console logged the error and made a vow (get it :) ) not to debug after midnight (given the typo i made that i think caused a couple of tickets recently, even if they did reveal deeper flaws) - im a bit wrapped up in some other things this week - can you look at the error on appveyor, where I put the console log and perhaps ask a windows buddy (i have none) whats up with the var server = net.createServer -> server.listen -> outputs this error:

```
err is %o { [Error: listen EACCES] code: 'EACCES', errno: 'EACCES', syscall: 'listen' }
C:\projects\node-portfinder\node_modules\vows\lib\vows.js:207
        console.log(console.result(results));
                ^
TypeError: undefined is not a function
    at process.<anonymous> (C:\projects\node-portfinder\node_modules\vows\lib\vows.js:207:17)
    at process.emit (events.js:107:17)
    at process.options.Emitter.emit (C:\projects\node-portfinder\node_modules\vows\lib\vows.js:240:24)
```

This error does not happen when i create non socket based servers in the other tests, so perhaps it has to do with the file system(that i dont understand in windows) that is making this throw or it could be something else, im not sure - its a bit hard to debug unless i can gain some context around the issue im trying to solve to make this error go away

thanks

**Comment by indexzero** [comment]
@eriktrom sorry for the delay in getting back to you. Two points to help you out here:

1. There are subtle things about sockets on Windows that I never quite understood, but `forever` implements: https://github.com/foreverjs/forever/blob/master/lib/forever/worker.js#L141-L154
2. If the above can't sort it out then I am fine with skipping the socket-based tests on Windows since the vast majority of users do simple port-based listening. Let's just add a TODO to revisit it later on though.

**Comment by eriktrom** [comment]
Bam - foreverjs hack worked first time, thanks @indexzero - we've got windows tests, w00t!

**Pull request merged**
